### ISSUE TITLE
Improve data-sly-resource runtime handling

### ISSUE THREAD

**Issue by tripodsan** [adobe/htlengine#11]
the goal is to improve the current resource handling from simply reading the file to a more pluggable mechanism.

for example, the `Runtime` could have a `ResourceHandler` delegation.

**Comment by megazear7** [comment]
@tripodsan I was looking into working on this improvement. Are there any additional details that you could provide as to how this should work?

**Comment by tripodsan** [comment]
a more sophisticated resource handling can be provided via a custom resource loader.
see https://github.com/adobe/htlengine/blob/6ffc90eb2e04b88c209fa78034754113fb6976fe/src/runtime/Runtime.js#L111
