### ISSUE TITLE
Use classes do not allow for paths outside of current folder

### ISSUE THREAD

**Issue by struct78** [adobe/htlengine#114]
A couple of things:

I think the update from 3.2.7 to 3.2.8 should have had a major version bump.

We have our project structure set up in a way that mimics the use of Java classes. For example, we have a simple file loader that outputs SVG code inline so it can be styled.

```
<sly data-sly-use.svg="${'com.companyname.project.InlineSvgUtility' @ svgPath=properties.logo}">
    ${logo.svgItem @ context='unsafe'}
</sly>
```

We then used the `withUseDirectory` method of the runtime to load modules from the 'modules/' folder in the root e.g. 

```
const fse = require('fs-extra')
const path = require('path')

class InlineSvgUtility {
  async use() {
    const assetsPath = 'assets/icons/'

    if (!this.svgPath) {
      return {
        svgItem: null,
      }
    }

    const data = await fse.readFile(path.join(assetsPath, this.svgPath), 'utf-8')

    return {
      svgItem: data,
    }
  }
}

module.exports = InlineSvgUtility
```

So this sits in `src/modules/com.companyname.project.InlineSvgUtility.js`, and was working happily. In 3.2.8 the withUseDirectory seems to effectively do nothing.

This line seems to be the cause.

https://github.com/adobe/htlengine/commit/6d0069874cb5fb14c8a39a109f19c9bbe90a829e#diff-59e501da46af5081071db46e7c50a748R243

If the path doesn't start with './' (e.g. '../'), it will attempt to resolve files relative to the folder the Compiler script is in, rather than the baseDir. For example, this will throw a "MODULE_NOT_FOUND" error.

```
<sly data-sly-use.svg="${'../modules/com.companyname.project.InlineSvgUtility' @ svgPath=properties.logo}">
    ${logo.svgItem @ context='unsafe'}
</sly>
```

I can fix it by traversing up 6 or so folders out of the node_modules, but that's not ideal.

```
<sly data-sly-use.svg="${'../../../../../../modules/com.companyname.project.InlineSvgUtility' @ svgPath=properties.logo}">
    ${logo.svgItem @ context='unsafe'}
</sly>
```

**Comment by tripodsan** [comment]
> I think the update from 3.2.7 to 3.2.8 should have had a major version bump.

yes. you're probably right.

the use classes now follow the nodejs require semantic. if the name doesn't start with a `./`, it is considered a global module, otherwise it is relative to the htl file. I think the bug here is that it doesn't check for `../`. so you could try to reference it with `./../modules/com.companyname.project.InlineSvgUtility.js`, depending where your `.htl` is.

another possibility could be to add the `src/modules` path to the module path when running your script. maybe you can play around with `NODE_PATH`.

@struct78 any chance our source code is public?

**Comment by struct78** [comment]
@tripodsan Here is some sample code that closely matches our setup https://github.com/struct78/htlengine-issue-114

**Comment by tripodsan** [comment]
thanks, I will look into it as soon as I have time....

**Comment by tripodsan** [comment]
ok, I see the problem. you are using the `compileToFunction()` which fakes the `module` and uses the `require` of the compiler.

**Comment by tripodsan** [comment]
nodejs 10.12 added: https://nodejs.org/docs/latest-v10.x/api/modules.html#modules_module_createrequirefrompath_filename

which would be an easy way to add the `useDirectory` to the module paths...
