### ISSUE TITLE
Support for identifiers containing a colon character

### ISSUE THREAD

**Issue by lachlanmcdonald** [adobe/htlengine#15]
At present, identifiers which contain a colon (`:`) will cause a syntax error to throw when running compiled code.

As a replacement, I suggest we replace the `:` with `$` during compilation for all variable names (include the provided globals); as the `$` is allowed in JavaScript but not the [HTL grammar](https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/master/SPECIFICATION.md#111-grammar). It is unlikely to conflict with any other variables within the compiled JS.

**Comment by lachlanmcdonald** [comment]
For that reason, maybe we should update the variable names for runtime methods to avoid conflicts with globals, particularly those in templates? Or throw an error when a variable is defined that matches one of these reversed names?

**Comment by tripodsan** [comment]
I would prefix all user defined variables and keep a lookup table during compilation. good idea to replace the `:` by `$`, though.
