### ISSUE TITLE
How to pass data into data-sly-use

### ISSUE THREAD

**Issue by panec** [adobe/htlengine#188]
I have a code that resolves data using some JS logic that I call to resolve the data for me.
I call it like this
```html
<sly data-sly-use.data="${'./data.js'}" />
```
in which I have something like this:
```js
module.exports = class Data {
 use() {
    return { "data": 123 };
  }
}
```
In there I can modify the object via some logic in the constructor on that class but the issue that I'm facing is a lack of ability to pass additional parameters / options. What I would love to do it to call something like this:
```html
<sly data-sly-use.data="${'./data.js' @ test = 123}" />
```
and access the additional params inside my data.js logic.

Currently the code generated is like this:
```js
const $use_0 = require("./data.js");

  return runtime.run(function* () {
    let $t, $n = $.dom.start();
    $.dom.text($n,"\n\n\n");
    const data = yield $.use($use_0, {"test": 123, });
```

How  to access the data passed via `$.use`? There is no documentation for it and I was not able to find how to do it.

**Comment by tripodsan** [comment]
similar to the use classes in AEM, the options are set as properties on your class: https://github.com/adobe/htlengine/blob/c206c5bf679fed2cec2d32fa6778140f586ae0f3/src/runtime/Runtime.js#L136


see an example use class: https://github.com/adobe/htlengine/blob/c206c5bf679fed2cec2d32fa6778140f586ae0f3/test/specs/use_spec/test_page.js#L12

and how it's used:
https://github.com/adobe/htlengine/blob/c206c5bf679fed2cec2d32fa6778140f586ae0f3/test/specs/use_spec.txt#L12

**Comment by panec** [comment]
Awesome. Thx for quick explanation. I should had snoop around spec files.
