### ISSUE TITLE
data-sly-attribute.style is not working

### ISSUE THREAD

**Issue by panec** [adobe/htlengine#201]
`data-sly-attribute.style` is not working as expected

This works
```
<a href="#whatever" style="color: ${colorName @ context='styleToken'};">Link</a>
```
while this does not work and returns no `style` attribute
```
<a href="#whatever" data-sly-attribute.style="color: ${colorName @ context='styleToken'};">Link</a>
```

Expected result is that both of them should behave the same.

**Comment by tripodsan** [comment]
thanks. I created a test: https://github.com/adobe/htlengine/pull/202 and look into it.

**Comment by karollewandowski** [comment]
`on*` and `style` attributes shouldn't be handled by `data-sly-attribute` block according to specification:
https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#223-attribute
> Event handler attributes (on*) and the style attribute cannot be generated with data-sly-attribute due to the fact that none of the available display contexts can fully protect against XSS attacks given the range of values that these attributes can contain.

**Comment by tripodsan** [comment]
thanks @karollewandowski. closing as won't fix.
