### ISSUE TITLE
data-sly-use.<templatePath> ignored when in template tag

### ISSUE THREAD

**Issue by benoit-adobe** [adobe/htlengine#208]
When `data-sly-use.<templatePath>` is used to load a template as an attribute on a `template` tag, it is not retrieve.

Found when trying to test the core components `navigation` with simple data, the component is recursive and it uses that in 2 files:
- [group.html](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/group.html#L16)
- [item.html](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/navigation/v1/navigation/item.html#L18-L19)

The template are not initialised unless `data-sly-use.<templatePath>` is put outside of the `template` tag.

**Comment by tripodsan** [comment]
thanks. I can reproduce it. also, the recursive resolution is a problem as well :-)

**Comment by tripodsan** [comment]
fixed with #220
