### ISSUE TITLE
Can we get rid of "it"?

### ISSUE THREAD

**Issue by trieloff** [adobe/htlengine#21]
Is there a way for us to make `it` implicit, so that all properties within `it` just become the global scope within HTL? That way `{it.request.path}` would become simply `{request.path}`.

**Comment by trieloff** [comment]
Might be something to do while we are breaking backward compatibility with existing scripts left and right ;)

**Comment by tripodsan** [comment]
htl engine already has support for globals.
see https://github.com/adobe/parcel-plugin-htl/issues/32
