### ISSUE TITLE
global variables ignored when in template tag 

### ISSUE THREAD

**Issue by jantimon** [adobe/htlengine#210]
Global variables can't be used within templates.

reproduction example:

template:

```html
<template data-sly-template.globalTest="${@ text}">
  <span data-sly-test="${wcmmode.edit}">Edit</span>
  <span data-sly-test="${!wcmmode.edit}">Live</span>
</template> 
```

compile time:
```js
const compiler = new Compiler()
    .withRuntimeVar([wcmmode])
```

run time:
```js
runtime.setGlobal({ wcmmode: {edit: true })
```

result:

```
TypeError: Cannot read property 'edit' of undefined
```

**Comment by tripodsan** [comment]
hmm, but here it works:

template:
- https://github.com/storybookjs/aem/blob/master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/commons/v1/templates.html

compiler:
- https://github.com/storybookjs/aem/blob/a9958dff5dc54958e9a20f51ef6b93fc66922c99/app/aem/src/server/framework-preset-aem.ts#L30
- https://github.com/storybookjs/aem/blob/a9958dff5dc54958e9a20f51ef6b93fc66922c99/app/aem/src/server/framework-preset-aem.ts#L30

runtime:
- https://github.com/storybookjs/aem/blob/a9958dff5dc54958e9a20f51ef6b93fc66922c99/app/aem/src/client/preview/render.ts#L42

**Comment by jantimon** [comment]
Thanks @tripodsan I investigated further and it looks like the problem was that I initialised the variables after the first run call:

```js
const runtime = new Runtime();
await run(runtime).catch(() => {});
runtime.setGlobal({ wcmmode: {edit: true })
const templates = runtime.template();
return runtime.run(function* () {
        const $n = runtime.dom.start();
        const allTemplates = runtime.template();
        yield runtime.call(templates["demo"], [
          $n,
          templateParameters,
        ]);
        return runtime.dom.end();
      });
```

I will try to find a workaround - thanks a lot for your support 👍

**Comment by tripodsan** [comment]
closing as 'works for me'
