### ISSUE TITLE
Add support for external template loading

### ISSUE THREAD

**Issue by tripodsan** [adobe/htlengine#217]
The current compilation inlines all the templates into the compiled script. This adds a lot of redundancy for larger projects with many components that share the same templates. 

## suggestion
It would be cool to have some kind of external template loader. along the lines of:

- add a new flag: `externalTemplates`
- define a `templateCompiler` that needs to return a function that it can invoke
- replace the template code in the component with a call to that function.
so the compiled code would still have the template functions as before, but it would only act as kind of proxy to the external template. so we don't need to change the entire template logic. maybe we can simplify later.

**Comment by jantimon** [comment]
Thank you so much for opening this issue 👍

I noticed that the compiler already has the information about the templates name in `c.name` here:  
https://github.com/adobe/htlengine/blob/a116ed737f557c08ead1c4a21671fa94a8b026a3/src/compiler/Compiler.js#L265-L271

So I could imagine an API similar to the TemplateLoader API:

```js
const externalTemplateLoader = (baseDir, uri, templateName) => {
  return `(templateArgs, runtime) => "Hello World"`
}

// Compile 
.withExternalTemplates(externalTemplateLoader)
```

With that API it would be also possible to make use of webpacks loader features e.g.:

```js
const externalTemplateLoader = (baseDir, uri, templateName) => {
     const resolvedPath = path.resolve(base, uri);
     return `(templateArgs, runtime) => 
       require('!!htl-template-loader!${resolvedPath}')
          .render('${templateName}', templateArgs, { globals: runtime.globals })`
}
```
