### ISSUE TITLE
Support Source Maps

### ISSUE THREAD

**Issue by trieloff** [adobe/htlengine#22]
So that we can debug HTL with `hlx up` (see adobe/helix-cli#162)

**Comment by dominique-pfister** [comment]
Committed a working approach (tested with Chrome devtools and VS Code).

Things that are still missing in the generated source map and would be nice to have:
- column numbers are currently 0, should rather reflect the actual location of a variable
- variables names are missing

**Comment by stefan-guggisberg** [comment]
supported in `hlx` as of [v0.7.12](https://github.com/adobe/helix-cli/releases/tag/v0.7.12)

**Comment by stefan-guggisberg** [comment]
reopening, sorry. didn't see 'missing tests' comment

**Comment by tripodsan** [comment]
I created a follow up issue: #28
