### ISSUE TITLE
Unable to set 'button' as `data-sly-element`

### ISSUE THREAD

**Issue by panec** [adobe/htlengine#223]
When calling following code when the value of `link` is false
```html
<button data-sly-element="${ link ? 'a' : 'button'}">test</button>
```
expected outcome is:
```html
<button>test</button>
```
but now it is
```html
<div>test</div>
```

**Comment by tripodsan** [comment]
I think change the element to `button` is not allowed per context. see https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#121-display-context

**Comment by raducotescu** [comment]
Yes, there's a limited number of elements that can be used with [`data-sly-element`](https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#224-element).

**Comment by panec** [comment]
@tripodsan while I agree that according to the spec it is not valid it is used in the official Adobe Core Components examples:
https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/button/v1/button/button.html
so I assume that it works in AEM environment. I would like to be able to have a parity of code between AEM implementation and the Node version.
@tripodsan @raducotescu what do you think about this inconsistency?

**Comment by tripodsan** [comment]
hmm..., I think the behaviour might be slightly different and is implement wrongly here:
since the original element is already a `<button/>`, changing to element name to `<a>` is allowed, but not to `<button/>` :-)
so instead of defaulting to `<div/>`, it should probably default to whatever was originally used.
