### ISSUE TITLE
variable defined by data-sly-use cannot be found unless it is lowercase

### ISSUE THREAD

**Issue by CodeByAlex** [adobe/htlengine#254]
Example from the Adobe 6.5 Core Components Library:
```
<button data-sly-use.button="com.adobe.cq.wcm.core.components.models.Button" data-sly-use.icontemplate="icon.html" data-sly-element="${button.link ? 'a' : 'button'}" class="cmp-button" href="${button.link}" aria-label="${button.accessibilityLabel}">
    <sly data-sly-call="${iconTemplate.icon @ icon=button.icon}"></sly>
    <span data-sly-test="${button.text}" class="cmp-button__text">${button.text}</span>
</button>
```
In this instance, we see the variable defined as data-sly-use.icontemplate but when used later in the HTL it is called with camel case ```<sly data-sly-call="${iconTemplate.icon @ icon=button.icon}"></sly>```. The htl engine cannot find the icontemplate variable so it throws the following exception:

![image](https://user-images.githubusercontent.com/29763590/97782639-0ab3be80-1b69-11eb-9b6b-f15d161375bd.png)

This is the case with all core components (from what I can tell) which either means that the htl engine should be picking up on the camel-cased usage or all of the core components that have multi-word variable names must be updated.

Proposal:

When checking the variable names in the htl for a match against the instantiated variable name, please run a toLowerCase() on each

Expected result:

```<sly data-sly-call="${iconTemplate.icon @ icon=button.icon}"></sly>``` should work properly if the variable is defined as  ```data-sly-use.icontemplate="icon.html"```

@tripodsan and I spoke about this offline
-----------

To test all of the core components against the htl engine, pull down the following branch of storybook-aem: ```https://github.com/storybookjs/aem/tree/include-support-3rd-party```
then:
1. run yarn from the root
2. run yarn build from the root
3. open a new terminal tab and cd into examples/aem-kitchen-sink
4. run yarn storybook.

You will then see all of the components in isolation:

![image](https://user-images.githubusercontent.com/29763590/97783165-53b94200-1b6c-11eb-894d-0c9525055cb3.png)

**Comment by tripodsan** [comment]
related: https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#211-identifiers

> Top top-level identifiers are case-insensitive (because they can be set through HTML attributes which are case-insensitive), but all their properties are case-sensitive.
