### ISSUE TITLE
itemList shorthand is broken

### ISSUE THREAD

**Issue by benoit-adobe** [adobe/htlengine#272]
It used to work but seems to be broken since the `lowercase/uppercase` insensitive updates.
For instance, it breaks when trying to render the WCM Core Components carousel with the error: `ReferenceError: itemlist is not defined`.
As a note, the carousel is using `data-sly-repeat`.

**Comment by tripodsan** [comment]
thanks for the issue. can you provide an example?

**Comment by benoit-adobe** [comment]
@tripodsan it happens when trying to render the `carousel` from the WCM Core Components with the JSON data examples from AEM Components site's [examples](https://www.aemcomponents.dev/content/core-components-examples/library/page-authoring/teaser.html), and the error is: `ReferenceError: itemlist is not defined`.

It used to work with a previous version of the `htlengine` but I am not sure which one to be honest (it seems to be broken since the `lowercase/uppercase` insensitive updates but not really sure).

I tried to change `itemList` to `itemlist` in the HTL template but it errors with the same message.

**Comment by tripodsan** [comment]
it's probably from here:
https://github.com/adobe/aem-core-wcm-components/blob/8e9280e9241e63face5a81a5b4744888ef24a0e1/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html#L36

**Comment by benoit-adobe** [comment]
@tripodsan FYI, `itemList` is a feature part of list/HTL, see `list` section in https://experienceleague.adobe.com/docs/experience-manager-htl/using/htl/block-statements.html?lang=en#htl.
