### ISSUE TITLE
data-sly-test.<variable name> not working

### ISSUE THREAD

**Issue by benoit-adobe** [adobe/htlengine#273]
It used to work but seems to be broken since the `lowercase/uppercase` insensitive updates.
For instance, it breaks when trying to render the WCM Core Components teaser with the error: `ReferenceError: hasContent is not defined`.
It is fixes when manually changing `hasContent` to `hascontent` in the template.

**Comment by tripodsan** [comment]
thanks for reporting. i'll have a look.
