### ISSUE TITLE
Compiler async support

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/htlengine#30]
The `Compiler` methods are currently all synchronous. Async methods would be more appropriate.

furthermore, `fs.*Sync` methods are used throughout the code base incl. tests. Those should be avoided by using `async/await` or `Promise` based variants provided by `fs-extra` instead.

**Comment by tripodsan** [comment]
-1 

I don't think this is needed. the compiler is mostly used on strings anyways, and adding async only complicates the process.  other drawbacks:

- an additional dependency to fs-extras
- incompatible change, i.e. need to fix all downstream users

Suggested tradeoff solution:
- only use async for functions that actually do I/O.

**Comment by stefan-guggisberg** [comment]
> and adding async only complicates the process

quoting some of your comments:
https://github.com/adobe/hypermedia-pipeline/pull/62#discussion_r223906174
https://github.com/adobe/hypermedia-pipeline/pull/62#discussion_r223906480

#32 doesn't complicate the process?

**Comment by stefan-guggisberg** [comment]
> * an additional dependency to fs-extras

AFAIK `fs-extra` is used in most (all?) of our helix-related projects, so that's hardly an issue. consumers of `htlengine` most likely already depend on `fs-extra`.

**Comment by stefan-guggisberg** [comment]
> * incompatible change, i.e. need to fix all downstream users

*all* downstream users, one? i volunteer to fix the consumer(s).
