### ISSUE TITLE
Case insensitivity breaks template call in 6.3.4

### ISSUE THREAD

**Issue by kuddl** [adobe/htlengine#301]
## Summary
Since 6.x some templates fail with the following error:
`Error: Template call that has not been registered.`

## Reason:

The template call will be compiled  **with camel cased** `primaryButton`:

```html
data-sly-call="${primaryButtonTmpl.primaryButton @  disableButton=false }"
```

```js 
yield $.call(primarybuttontmpl["primaryButton"], [$n, {"disableButton": false, }]);
```

however the template definition will be compiled **with lower case** `primarybutton`:

```html
<template data-sly-template.primaryButton="${@ disableButton }">
```

```js
   $.template('primaryButton.htl', 'primarybutton', primarybutton);
```

## Full reproduction example:

main.htl:
```html
<sly
        data-sly-use.primaryButtonTmpl="./primaryButton.htl"
        data-sly-call="${primaryButtonTmpl.primaryButton @  disableButton=false }"
    >
</sly>
```

primaryButton.htl:
```html
<template data-sly-template.primaryButton="${@ disableButton }">
    <button>hello</button>
</template>
```

**Comment by tripodsan** [comment]
this should be fixed in 6.3.4.....

**Comment by tripodsan** [comment]
I'll try to reproduce it....

**Comment by jantimon** [comment]
Maybe we could change `<div data-sly-call="${lv.item ` in https://github.com/adobe/htlengine/commit/94937194b3cc88e7e2992fce963e5354dd4100b2 to `<div data-sly-call="${lv.demoItem ` to test the lowercasing
