### ISSUE TITLE
6.3.4 adds Proxy and breaks IE11 support

### ISSUE THREAD

**Issue by jantimon** [adobe/htlengine#303]
```
function createTemplateGroup() {
  return new Proxy({ }, {
    get: (obj, key) => obj[key.toLowerCase()],
    set: (obj, key, value) => {
      // eslint-disable-next-line no-param-reassign
      obj[key.toLowerCase()] = value;
      return true;
    },
  });
}
```

this code causes multiple issues for us:

`createTemplateGroup().keys()` doesn't work anymore and breaks https://github.com/jantimon/htl-template-loader/blob/3ea0f0ee163fdc5c6b0e882d4174c6b269d78c99/lib/template-api.js#L130-L131

`Proxy` is not supported in IE11

Is there any way to parse `data-sly-call="${headlineTemplate.headlineDemo}`?  
Because in that case we wouldn't need to compile incorrect code and fix it in the runtime with a Proxy

**Comment by tripodsan** [comment]
ok...I look for a different option...

but who in his right mind still uses IE 11 ? :-))

**Comment by jantimon** [comment]
Unfortunately most of our clients who can afford using AEM are giant coronations which use IE11 internally

**Comment by kuddl** [comment]
@tripodsan Thanks a lot for fixing of the issues about proxy and lowercase so quickly. It really helped a lot and was much appreciated. 
Keep up the great work! 
👏 👍 💯
