### ISSUE TITLE
Tests fail on Windows 7x64

### ISSUE THREAD

**Issue by cookch10** [adobe/htlengine#34]
Hello,

I recently cloned this project and installed the dependencies then attempted to run the tests when I noticed there are a number of tests failing.  I am on Windows 7 x64 OS Node v8.9.3.  I have attached a log of the test output.  Looking forward to using this library!
[adobe-htl-test-output-fail.log](https://github.com/adobe/htlengine/files/2653950/adobe-htl-test-output-fail.log)

**Comment by dominique-pfister** [comment]
Cool, thanks for reporting!

Problem was the `require` of a verbatim file name in the template: directory separators in Windows (backslashes) need to be escaped twice when written to a file.
