### ISSUE TITLE
Engine gets really slow for large HTML documents

### ISSUE THREAD

**Issue by tripodsan** [adobe/htlengine#38]
adding some tests with larger files reveals:

```
  HTML Parsing
    ✓ parses simple.htm
    ✓ parses 400kb.htm (114ms)
    ✓ parses 700kb.htm (152ms)

  HTML Parsing and Processing
    ✓ parses and processes simple.htm (155ms)
    ✓ parses and processes 400kb.htm (16616ms)
    ✓ parses and processes 700kb.htm (26194ms)
```

it seems that the HTML parser is reasonably fast, but the processing (i.e. converting the HTML DOM into the HTL command stream is slow.

**Comment by tripodsan** [comment]
we could try https://github.com/fb55/htmlparser2, which seems veery fast.... and then operate on the dom instead of using a handler. maybe this way we can easily skip non-htl tags quicker.

and then maybe use the dom directly to generate the JS instead of creating the command stream first.

another problem might be the size of the JS. maybe using a Buffer would perform better than just appending to a string.

**Comment by tripodsan** [comment]
slight improvement:

```
  HTML Parsing and Processing
    ✓ parses and processes simple.htm (135ms)
    ✓ parses and processes 400kb.htm (5470ms)
    ✓ parses and processes 700kb.htm (7774ms)
```

**Comment by tripodsan** [comment]
also testing actual engine performance (including js generation).:

```
  Engine Performance test
    ✓ produces htl output for simple2.html (114ms)
    ✓ produces htl output for 400kb.htm (5605ms)
    ✓ produces htl output for 700kb.htm (7853ms)
```

this only adds very little to the process time.

**Comment by tripodsan** [comment]
even better now, when not using the HTL parser if not needed:

```
  HTML Parsing and Processing
    ✓ parses and processes simple.htm (97ms)
    ✓ parses and processes 400kb.htm (108ms)
    ✓ parses and processes 700kb.htm (129ms)
```

maybe switch to a non antlr4 based parser? or improve the antlr4 one?

**Comment by DrewML** [comment]
> maybe switch to a non antlr4 based parser

I was actually just going to comment about antlr4 here 😂 - great timing. This issue piqued my interest quite a bit.

I pared down the tests in that file and made thinks synchronous, just to make profiling the `700kb.htm` run a bit simpler. I began the profiling run right when the `debugger` statement was hit.

```js
const largeFile = fse.readFileSync(path.resolve(__dirname, 'templates', '700kb.htm'), 'utf8');

/**
 * Simple tests that check if the parser can process all the expressions
 */
describe('HTML Parsing and Processing', () => {
  debugger;  // profiling begins
  it('parses and processes largeFile', () => {
    const handler = new MarkupHandler(new CommandStream());
    HTMLParser.parse(largeFile, handler);
    assert.equal(handler.result, largeFile);
  }).timeout(30000);
});
```

![image](https://user-images.githubusercontent.com/5233399/51296183-73579880-19e0-11e9-8a7f-1e50b617dd91.png)

Seems like the large majority of the slowness is from the parser. That `closureCheckingStopState` method looks like a super expensive recursive function. The call stacks are _massive_:

![image](https://user-images.githubusercontent.com/5233399/51296315-37710300-19e1-11e9-91aa-ea15d91488e7.png)

A google search for `closureCheckingStopState` references several issues relating to slowness or OOM problems.

**Comment by tripodsan** [comment]
> I was actually just going to comment about antlr4 here 😂 - great timing. This issue piqued my interest quite a bit.

yeah...I saw this tool. we just took over the antlr4 grammars from the java implementation. and also followed more or less their implementation architecture.

If I would start again, I would do it differently. probably a home-grown parser, or a simpler grammar, or not having inline code in the grammar would make it easier to understand.
