### ISSUE TITLE
use statement cannot load external templates

### ISSUE THREAD

**Issue by kptdobe** [adobe/htlengine#47]
The spec states that the [use](https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#221-use) statement can be used to load external templates (last sentence of the section). The following example does not work:

```
<div data-sly-use.lib="templateLib.html" data-sly-call="${lib.one}"></div>
```

where `templateLib.html` is 

```
<template data-sly-template.one>blah</template>
``` 

You get an error like: `SyntaxError: Unexpected token <`

**Comment by kptdobe** [comment]
They are and they work (except the "call from external file" case)! ;)

https://github.com/adobe/htlengine/blob/master/src/parser/plugins/TemplatePlugin.js

You can try that in you htl file, this works:

```
 <template data-sly-template.one="${@content}">
   <h1>${content.title}</h1>
 </template>

<div data-sly-call="${one @content=content}"></div>
```

**Comment by kptdobe** [comment]
Useful, I do not know yet, I am exploring the idea of having a template per section for example. But having all of them in the same file gets quickly unreadable.

**Comment by tripodsan** [comment]
Really? I don't remember having implemented them :-)
