### ISSUE TITLE
[XSS] URLs are not correctly sanitized

### ISSUE THREAD

**Issue by rofe** [adobe/htlengine#53]
[xss_api#sanitizeUrl](https://github.com/adobe/htlengine/blob/35e286e32e54c3748c7b0f9cf95c313909e45f60/src/runtime/xss_api.js#L95) does not correctly sanitize URLs.

Sample HTL:
```
<a href="${url}">XSS Link</a>
```
Executed with URL:
```
javascript:alert(0)
```
Expected Result:
```
<a href="javascript&#x3a;alert&#x28;0&#x29;">XSS Link</a>
```
(or some other form of encoding or omission)

Actual Result:
```
<a href="javascript:alert(0)">XSS Link</a>
```

**Comment by rofe** [comment]
Added (failing) tests in `xss-tests` branch.

**Comment by tripodsan** [comment]
can you add the tests to #54 ?

**Comment by rofe** [comment]
I could, but they would still fail. #54 deals with context `html` not `uri`...

**Comment by rofe** [comment]
From https://github.com/adobe/htlengine/pull/54#issuecomment-489877196 (@tripodsan):

why not just use the same regexp as in sling:

This is the regexp Sling uses to validate href's:
https://github.com/apache/sling-org-apache-sling-xss/blob/5071a142cdfeaf128a0db1ed5222b4e3753303c9/src/main/resources/SLING-INF/content/config.xml#L76

built from this code:
https://github.com/apache/sling-org-apache-sling-xss/blob/5071a142cdfeaf128a0db1ed5222b4e3753303c9/src/main/java/org/apache/sling/xss/impl/XSSFilterImpl.java#L84

**Comment by ramboz** [comment]
I copied over the Sling regexp and adapted to JS.

@rofe Note that in the tests you added, there is more than just the URI sanitization. You also inject whole elements which doesn't use the same context.

It also seems that by default, the htlengine outputs variables in `unsafe` context…

`data.js`
```javascript
{foo: "<a href="javascript:alert(0)">XSS Link</a>"}
```

`tpl.htl`
```
${foo}
```

`tpl.html`
```html
<a href="javascript:alert(0)">XSS Link</a>
```

But with the proper `html`, this is properly escaped:

`tpl.htl`
```
${foo @ context='html'}
```

`tpl.html`
```html
<a>XSS Link</a>
```

I'm still trying to figure out how the default context is set. At the moment, my guess is that the parser does not set it.

**Comment by rofe** [comment]
The default context should be `html` I guess...
