### ISSUE TITLE
XSS escaping completely removes src/href attributes on images and links

### ISSUE THREAD

**Issue by ramboz** [adobe/htlengine#66]
With #53 the XSS escaping introduced ends up being a bit too zealous and removes all:
- `src` attributes on `images`
- `href` attributes on `links`

**Comment by tripodsan** [comment]
- hmm, what's the behavior in sling when you output `<a href="www.github.com">` in the HTML context?
- what's the performance impact?

**Comment by ramboz** [comment]
- `${'<a href="www.google.com">Foo</a>' @ context='unsafe'}` or `html` both output only `Foo` as far as I can tell, which surprises me actually.
- impact should be minimal as we only apply a minimal overhead of img/a tags on the existing sanitization logic. the tags are parsed anyway, we only treat their links differently

**Comment by tripodsan** [comment]
> So if we follow the sling behavior, we actually can't even output html from the markdown inside the template it would seem…

that would be weird, if `unsafe` doesn't work as expected in sling... 

In any case, once we add the DOM support (#62), we the XSS escaping become less important.

**Comment by ramboz** [comment]
> that would be weird, if unsafe doesn't work as expected in sling...

Maybe our expectations are wrong, I'm not sure, but my tests clearly didn't let me inject any complex HTML via a variable.
